apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: graph-client
  name: graph-client
spec:
  revisionHistoryLimit: 0
  template:
    metadata:
      annotations:
        chaos.alpha.kubernetes.io/enabled: "true"
      labels:
        name: graph-client
    spec:
      containers:
      - name: graph-client
        image: vizzuality/graph-client
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "0.5"
            memory: "256M"
          limits:
            cpu: "1"
            memory: "512M"
        args:
          - start
        env:
          - name: PORT
            value: "4500"
          - name: NODE_ENV
            value: prod
          - name: NODE_PATH
            value: app/src
          - name: LOCAL_URL
            value: http://graph-client.default.svc.cluster.local:4500
          - name: NEO4J_URI
            valueFrom:
                secretKeyRef:
                  name: dbsecrets
                  key: NEO4J_URI
          - name: NEO4J_USER
            valueFrom:
                secretKeyRef:
                  name: dbsecrets
                  key: NEO4J_USER
          - name: NEO4J_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: dbsecrets
                  key: NEO4J_PASSWORD
          - name: CT_URL
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_URL
          - name: CT_TOKEN
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_TOKEN
          - name: CT_REGISTER_MODE
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: CT_REGISTER_MODE
          - name: API_VERSION
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: API_VERSION

        ports:
          - containerPort: 4500
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /healthcheck
            port: 4500
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 15
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /healthcheck
            port: 4500
          failureThreshold: 3
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 15

      restartPolicy: Always
