apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: graph-client
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: graph-client
  minReplicas: 2
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
